title: nullm4ri
description: Suhyun's development blog
remote_theme: just-the-docs/just-the-docs

url: https://nullm4ri.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
