version: "3.5"

services:
  jekyll:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app/pages
#    stdin_open: true
#    tty: true
    command: bundle exec jekyll serve --config pages/_config_local.yml -H 0.0.0.0 -t
